Repository intel-retail/loss-prevention, pull requests merged in 2024-11, with the labels that each got.

#16 feat: add/update benchmark of loss prevention pipelines documentation and make targets
  .gitignore
  Makefile
  README.md
  benchmark.md
Labels: documentation, enhancement

#19 feat: Adding second ROI and alert logic
  Makefile
  src/app/loss_prevention.py
  src/docker-compose.yml
  src/extensions/gva_roi_metadata.py
  src/pipelines/roi.json
  src/pipelines/yolov8s_roi.sh
Labels: enhancement

#18 Benchmark multiple different pipelines running in parallel
  Makefile
  benchmark.md
  src/docker-compose-2-clients.yml
  src/entrypoint.sh
  src/pipelines/age_recognition.sh
  src/pipelines/people_detection.sh
  src/pipelines/yolov5s.sh
  src/pipelines/yolov5s_effnetb0.sh
  src/pipelines/yolov5s_full.sh
  src/pipelines/yolov8s_roi.sh
Labels: enhancement, 3.2

#22 Update GitHub actions workflows
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/gotest.yaml
  .github/workflows/integration.yaml
  .github/workflows/reports.yaml
  .github/workflows/reviewdog.yaml
  .github/workflows/scorecard.yml
  .github/workflows/trivy-scan.yaml
  .github/workflows/trivyimagescan.yaml
Labels: enhancement

#21 feat: Integrating grafana to display data
  src/app/Dockerfile
  src/app/loss_prevention.py
  src/docker-compose.yml
  src/grafana/provisioning/dashboard-actual/dashboard.json
  src/grafana/provisioning/dashboards/default.yml
  src/grafana/provisioning/datasources/default.yml
  src/pipelines/yolov8s_roi.sh
Labels: enhancement
