Repository intel-retail/loss-prevention, pull requests merged in 2025-04, with the labels that each got.

#40 feat(docker): Update python version of src/weightScale/Dockerfile
  src/weightScale/Dockerfile
Labels: enhancement, oss_hackathon

#48 fix: Update codeql version
  .github/workflows/codeql.yaml
  .github/workflows/trivy-scan.yaml
  .github/workflows/trivyimagescan.yaml
Labels: bug, cicd

#58 fix: update input video URL
  Makefile
Labels: bug
