Repository intel-retail/loss-prevention, pull requests merged in 2025-02, with the labels that each got.

#30 fix: Move ISSUE_TEMPLATE.md to ISSUETEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug, Beginner

#32 fix: Change pep8 to pycodestyle for fixing failure due to reviewdog GitHub action
  .github/.reviewdogConfig.yml
  .github/workflows/reviewdog.yaml
Labels: bug, Beginner, cicd

#39 docs: Add grafana documentation and Makefile changes
  Makefile
  README.md
  grafana.jpg
Labels: documentation
